# Generated by Django 5.1.14 on 2026-06-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_id', models.CharField(blank=True, help_text='Unique FAQ identifier (automatically generated).', max_length=50, unique=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('target_audience', models.CharField(choices=[('business', 'Business'), ('creator', 'Creator'), ('both', 'Both')], default='both', help_text='Determine whether this FAQ shows for businesses, creators, or both.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Only active FAQs will be shown in the dashboards.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
    ]
