# Generated by Django 6.0.2 on 2026-08-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FAQ", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="type",
            field=models.CharField(
                choices=[
                    ("all", "All Campaigns"),
                    ("pitch", "Pitch Campaign"),
                    ("request", "Request Campaign"),
                    ("direct_request", "Direct Request Campaign"),
                ],
                default="all",
                help_text="Choose which type of campaign this FAQ applies to.",
                max_length=50,
            ),
        ),
    ]
