# Generated by Django 6.0.2 on 2026-08-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FAQ", "0002_faq_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="type",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("payment", "Payment"),
                    ("campaign", "Campaign"),
                    ("profile", "Profile"),
                ],
                default="all",
                help_text="Choose which type of campaign this FAQ applies to.",
                max_length=50,
            ),
        ),
    ]
