# Generated by Django 5.1.14 on 2026-06-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_complaint_priority_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='support_attachments/'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='is_voice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
