# Generated by Django 6.0.2 on 2026-07-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquire", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="role",
            field=models.CharField(
                choices=[
                    ("brand", "Brand / Brand Representative"),
                    ("creator", "Creator / Influencer"),
                    ("agency", "Agency Partner"),
                    ("service_provider", "Service Provider"),
                    ("other", "Other Inquiry"),
                ],
                default="brand",
                max_length=20,
            ),
        ),
    ]
