# Generated by Django 6.0.2 on 2026-09-02 05:22

from django.db import migrations, models


def remap_guide_audiences(apps, schema_editor):
    Guide = apps.get_model("guide", "Guide")
    for g in Guide.objects.all():
        audience = (g.target_audience or "").lower()
        if "both" in audience:
            g.target_audience = "both"
            if g.guide_id and not g.guide_id.endswith("-BO"):
                g.guide_id = g.guide_id[:7] + "-BO" if len(g.guide_id) >= 7 else g.guide_id + "-BO"
            g.save()
        elif "business" in audience or "brand" in audience:
            g.target_audience = "business"
            if g.guide_id and not g.guide_id.endswith("-BU"):
                g.guide_id = g.guide_id[:7] + "-BU" if len(g.guide_id) >= 7 else g.guide_id + "-BU"
            g.save()
        else:
            g.target_audience = "creator"
            if g.guide_id and not g.guide_id.endswith("-CR"):
                g.guide_id = g.guide_id[:7] + "-CR" if len(g.guide_id) >= 7 else g.guide_id + "-CR"
            g.save()


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(remap_guide_audiences, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="guide",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("business", "Business"),
                    ("creator", "Creator"),
                    ("both", "Both"),
                ],
                default="creator",
                help_text="Target audience who can access and view this guide (Business, Creator, or Both).",
                max_length=50,
            ),
        ),
    ]
