# Generated by Django 6.0.2 on 2026-09-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0002_alter_guide_target_audience"),
    ]

    operations = [
        migrations.AddField(
            model_name="guide",
            name="document",
            field=models.FileField(
                blank=True,
                help_text="Upload an optional document, PDF, handbook, or attachment for this guide.",
                null=True,
                upload_to="guide_documents/",
            ),
        ),
    ]
