# Generated by Django 5.1.14 on 2026-06-08 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Live', 'Live'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('brief', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_language', models.CharField(blank=True, max_length=100, null=True)),
                ('voice_brief', models.CharField(blank=True, max_length=255, null=True)),
                ('screenshare_brief', models.CharField(blank=True, max_length=255, null=True)),
                ('video_brief', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_review', models.TextField(blank=True, help_text='Provide review/rejection comments to the business if rejected.', null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_campaigns', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminComplianceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Escrow Protection', 'Escrow Protection'), ('Contract Scope Dispute', 'Contract Scope Dispute'), ('Safety / Guidelines', 'Safety / Guidelines'), ('Deliverable Audit', 'Deliverable Audit')], max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Pending Review', 'Pending Review'), ('Resolved', 'Resolved'), ('Approved', 'Approved')], default='Pending Review', max_length=50)),
                ('reply', models.TextField(blank=True, default='')),
                ('date', models.CharField(blank=True, default='Just now', max_length=100)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='campegin.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_done', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='campegin.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_done', models.BooleanField(default=False)),
                ('due_date', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='campegin.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Revision Requested', 'Revision Requested'), ('Approved', 'Approved'), ('Published', 'Published')], default='Revision Requested', max_length=50)),
                ('deadline', models.CharField(blank=True, max_length=100, null=True)),
                ('brief', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, default='')),
                ('screenshot_name', models.CharField(blank=True, default='', max_length=255)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='campegin.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Released', 'Released'), ('In Escrow', 'In Escrow'), ('Funded', 'Funded')], max_length=30)),
                ('payment_date', models.CharField(blank=True, default='', max_length=100)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='campegin.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='campegin.campaign')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('file_attachment', models.CharField(blank=True, default='', max_length=255)),
                ('time', models.CharField(max_length=50)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='campegin.campaign')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
