# Generated by Django 5.1.14 on 2026-06-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campegin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Campaign Category',
                'verbose_name_plural': 'Campaign Categories',
            },
        ),
        migrations.CreateModel(
            name='CampaignDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Campaign Deliverable',
                'verbose_name_plural': 'Campaign Deliverables',
            },
        ),
        migrations.CreateModel(
            name='CampaignLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Campaign Language',
                'verbose_name_plural': 'Campaign Languages',
            },
        ),
        migrations.CreateModel(
            name='CampaignPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Campaign Platform',
                'verbose_name_plural': 'Campaign Platforms',
            },
        ),
    ]
