# Generated by Django 6.0.2 on 2026-07-10 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0002_campaigncategory_campaigndeliverable_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pitch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campaign_name", models.CharField(max_length=255)),
                ("budget", models.DecimalField(decimal_places=2, max_digits=12)),
                ("sent_date", models.CharField(max_length=100)),
                ("tags", models.JSONField(blank=True, default=list, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("counter_offer", "Counter Offer"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("deliverables", models.JSONField(blank=True, default=list, null=True)),
                (
                    "counter_offer",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_pitches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_pitches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
