# Generated by Django 6.0.2 on 2026-07-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0003_pitch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="screenshare_brief",
            field=models.FileField(blank=True, null=True, upload_to="brief_media/"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="video_brief",
            field=models.FileField(blank=True, null=True, upload_to="brief_media/"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="voice_brief",
            field=models.FileField(blank=True, null=True, upload_to="brief_media/"),
        ),
    ]
