# Generated by Django 6.0.2 on 2026-07-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0004_alter_campaign_screenshare_brief_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverable",
            name="assetDriveLink",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="deliverable",
            name="assetFileName",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="deliverable",
            name="status",
            field=models.CharField(
                choices=[
                    ("Revision Requested", "Revision Requested"),
                    ("Pending Review", "Pending Review"),
                    ("Approved", "Approved"),
                    ("Published", "Published"),
                ],
                default="Revision Requested",
                max_length=50,
            ),
        ),
    ]
