# Generated by Django 6.0.2 on 2026-07-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campegin",
            "0005_deliverable_assetdrivelink_deliverable_assetfilename_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverable",
            name="er",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="deliverable",
            name="reach",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="deliverable",
            name="views",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
