# Generated by Django 6.0.2 on 2026-07-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0006_deliverable_er_deliverable_reach_deliverable_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverable",
            name="assetFileName",
            field=models.FileField(blank=True, null=True, upload_to="deliverables/"),
        ),
        migrations.AlterField(
            model_name="deliverable",
            name="screenshot_name",
            field=models.FileField(blank=True, null=True, upload_to="deliverables/"),
        ),
    ]
