# Generated by Django 6.0.2 on 2026-07-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0007_alter_deliverable_assetfilename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="medium",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
