# Generated by Django 6.0.2 on 2026-07-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0008_campaign_country_campaign_medium"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="district",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="province",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="medium",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
