# Generated by Django 6.0.2 on 2026-07-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0009_campaign_district_campaign_province_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="counter_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="counter_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Live", "Live"),
                    ("Completed", "Completed"),
                    ("Rejected", "Rejected"),
                    ("Countered", "Countered"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
    ]
