# Generated by Django 6.0.2 on 2026-07-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0010_campaign_counter_note_campaign_counter_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Live", "Live"),
                    ("Completed", "Completed"),
                    ("Rejected", "Rejected"),
                    ("Countered", "Countered"),
                    ("Under_Review", "Under Review"),
                ],
                default="Under_Review",
                max_length=30,
            ),
        ),
    ]
