# Generated by Django 6.0.2 on 2026-07-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0011_alter_campaign_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacemessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("main", "Main Chat"),
                    ("admin_note", "Admin Private Note"),
                    ("admin_business", "Admin-Business Chat"),
                    ("admin_creator", "Admin-Creator Chat"),
                ],
                default="main",
                max_length=20,
            ),
        ),
    ]
