# Generated by Django 6.0.2 on 2026-07-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0012_workspacemessage_message_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="end_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
