# Generated by Django 6.0.2 on 2026-07-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0013_campaign_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="decline_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
