# Generated by Django 6.0.2 on 2026-07-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0014_campaign_decline_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="pitch",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="pitch_attachments/"
            ),
        ),
        migrations.AddField(
            model_name="pitch",
            name="decline_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="budget",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
