# Generated by Django 6.0.2 on 2026-07-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0015_pitch_attachment_pitch_decline_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="counter_round",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Live", "Live"),
                    ("Completed", "Completed"),
                    ("Rejected", "Rejected"),
                    ("Countered_Pending", "Creator Counter Pending Approval"),
                    ("Countered", "Countered"),
                    ("Business_Counter_Pending", "Business Counter Pending Approval"),
                    ("Business_Countered", "Business Countered"),
                    ("Under_Review", "Under Review"),
                ],
                default="Under_Review",
                max_length=50,
            ),
        ),
    ]
