# Generated by Django 6.0.2 on 2026-07-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0016_campaign_counter_round_alter_campaign_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="created_via",
            field=models.CharField(
                choices=[("request", "Direct Request"), ("pitch", "Creator Pitch")],
                default="request",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_admin", "Pending Admin Approval"),
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("counter_offer", "Counter Offer"),
                ],
                default="pending_admin",
                max_length=30,
            ),
        ),
    ]
