# Generated by Django 6.0.2 on 2026-07-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0017_campaign_created_via_alter_pitch_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="pitch",
            name="counter_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_admin", "Pending Admin Approval"),
                    ("pending", "Pending Business Review"),
                    ("counter_offer", "Counter Offer by Business"),
                    ("pitch_counter_pending", "Creator Counter – Pending Admin"),
                    ("pitch_countered", "Creator Counter – Approved"),
                    ("biz_counter_pending", "Business Counter – Pending Admin"),
                    ("biz_countered", "Business Counter – Approved"),
                    ("accepted", "Accepted – Converted to Campaign"),
                    ("declined", "Declined"),
                ],
                default="pending_admin",
                max_length=30,
            ),
        ),
    ]
