# Generated by Django 6.0.2 on 2026-07-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0018_pitch_counter_note_alter_pitch_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="pitch",
            name="counter_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_admin", "Pending Admin Approval"),
                    ("pending", "Pending Business Review"),
                    (
                        "accepted_by_business",
                        "Accepted by Business – Awaiting Admin Conversion",
                    ),
                    ("accepted", "Accepted – Converted to Campaign"),
                    ("biz_counter_pending", "Business Counter – Pending Admin"),
                    ("biz_countered", "Business Counter – Approved"),
                    ("pitch_counter_pending", "Creator Counter – Pending Admin"),
                    ("pitch_countered", "Creator Counter – Approved"),
                    ("declined", "Declined"),
                ],
                default="pending_admin",
                max_length=35,
            ),
        ),
    ]
