# Generated by Django 6.0.2 on 2026-07-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0019_pitch_counter_count_alter_pitch_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="counter_history",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="pitch",
            name="counter_history",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
