# Generated by Django 6.0.2 on 2026-07-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0020_campaign_counter_history_pitch_counter_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverable",
            name="revision_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="deliverable",
            name="revision_reference_file",
            field=models.FileField(
                blank=True, null=True, upload_to="deliverables/revisions/"
            ),
        ),
        migrations.AddField(
            model_name="deliverable",
            name="revision_reference_link",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
