# Generated by Django 6.0.2 on 2026-07-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0021_deliverable_revision_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigndeliverable",
            name="max_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="campaigndeliverable",
            name="min_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
