# Generated by Django 6.0.2 on 2026-07-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0022_campaigndeliverable_max_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaigndeliverable",
            name="max_price",
        ),
        migrations.RemoveField(
            model_name="campaigndeliverable",
            name="min_price",
        ),
        migrations.AddField(
            model_name="campaigncategory",
            name="max_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="campaigncategory",
            name="min_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
    ]
