# Generated by Django 6.0.2 on 2026-07-28 17:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0023_remove_campaigndeliverable_max_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaigncategory",
            name="max_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=50000.0,
                max_digits=12,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("10000.00"))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="campaigncategory",
            name="min_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=10000.0,
                max_digits=12,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("10000.00"))
                ],
            ),
        ),
    ]
