# Generated by Django 6.0.2 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0024_alter_campaigncategory_max_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigncategory",
            name="duration",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="campaigncategory",
            name="platform",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="campaigncategory",
            name="type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="campaigncategory",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
