# Generated by Django 6.0.2 on 2026-07-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campegin",
            "0025_campaigncategory_duration_campaigncategory_platform_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignNiche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Checked = active/visible while creating campaign; Unchecked = inactive/hidden",
                        verbose_name="Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Niche",
                "verbose_name_plural": "Campaign Niches",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="campaigncategory",
            name="max_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="campaigncategory",
            name="min_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
    ]
