# Generated by Django 6.0.2 on 2026-08-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0026_campaignniche_alter_campaigncategory_max_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="max_budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="max_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="min_budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="min_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="per_creator_budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
