# Generated by Django 6.0.2 on 2026-08-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0027_campaign_max_budget_campaign_max_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="rate_card_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
