# Generated by Django 6.0.2 on 2026-08-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0028_campaign_rate_card_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="created_via",
            field=models.CharField(
                choices=[
                    ("direct_request", "Direct Request"),
                    ("request", "Request"),
                    ("pitch", "Creator Pitch"),
                ],
                default="direct_request",
                max_length=50,
            ),
        ),
    ]
