# Generated by Django 6.0.2 on 2026-08-03 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0029_alter_campaign_created_via"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="admincomplianceticket",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="admincomplianceticket",
            name="sender_role",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
