# Generated by Django 6.0.2 on 2026-08-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0030_admincomplianceticket_sender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admincomplianceticket",
            name="target_audience",
            field=models.CharField(blank=True, default="both", max_length=50),
        ),
    ]
