# Generated by Django 6.0.2 on 2026-08-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0031_admincomplianceticket_target_audience"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigndeliverable",
            name="platform",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="campaigndeliverable",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
