# Generated by Django 6.0.2 on 2026-08-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0032_campaigndeliverable_platform_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignplatform",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="platform_logos/"),
        ),
    ]
