# Generated by Django 6.0.2 on 2026-08-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0033_alter_campaignplatform_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="created_time",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
