# Generated by Django 6.0.2 on 2026-08-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0034_campaign_created_at_campaign_created_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacemessage",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
