# Generated by Django 6.0.2 on 2026-08-21 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0035_workspacemessage_is_pinned"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigndeliverable",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliverables",
                to="campegin.campaigncategory",
            ),
        ),
    ]
