# Generated by Django 6.0.2 on 2026-08-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0036_campaigndeliverable_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="campaign_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="niche",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
