# Generated by Django 6.0.2 on 2026-08-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0037_campaign_campaign_category_campaign_niche"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverable",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_SUBMISSION", "Pending Submission"),
                    ("PENDING_BUSINESS_REVIEW", "Pending Business Review"),
                    ("REVISION_REQUIRED", "Revision Required"),
                    ("PENDING_ADMIN_APPROVAL", "Pending Admin Approval"),
                    ("PUBLISHED", "Published"),
                    ("Revision Requested", "Revision Requested"),
                    ("Pending Review", "Pending Review"),
                    ("Approved", "Approved"),
                ],
                default="PENDING_SUBMISSION",
                max_length=50,
            ),
        ),
    ]
