# Generated by Django 6.0.2 on 2026-08-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0038_alter_deliverable_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="platform",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
