# Generated by Django 6.0.2 on 2026-08-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0039_campaign_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="pitch",
            name="end_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pitch",
            name="platform",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pitch",
            name="start_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
