# Generated by Django 6.0.2 on 2026-08-24 01:55

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0040_pitch_end_date_pitch_platform_pitch_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Live", "Live"),
                    ("Completed", "Completed"),
                    ("Rejected", "Rejected"),
                    ("Countered_Pending", "Creator Counter Pending Approval"),
                    ("Countered", "Countered"),
                    ("Business_Counter_Pending", "Business Counter Pending Approval"),
                    ("Business_Countered", "Business Countered"),
                    (
                        "Accepted_Pending_Admin",
                        "Counter Accepted Pending Admin Approval",
                    ),
                    ("Under_Review", "Under Review"),
                ],
                default="Under_Review",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="campaigndeliverable",
            name="category",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliverables",
                to="campegin.campaigncategory",
            ),
        ),
    ]
