# Generated by Django 6.0.2 on 2026-08-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0041_alter_campaign_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaigncategory",
            name="duration",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="campaigncategory",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="campaigncategory",
            name="platform",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="campaigncategory",
            name="type",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
