# Generated by Django 6.0.2 on 2026-08-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campegin", "0042_alter_campaigncategory_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pitch",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pitch",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pitch",
            name="delivery_languages",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="pitch",
            name="district_city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pitch",
            name="niche",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pitch",
            name="niches",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="pitch",
            name="province_state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Live", "Live"),
                    ("Completed", "Completed"),
                    ("Rejected", "Rejected"),
                    ("Countered_Pending", "Creator Counter Pending Approval"),
                    ("Countered", "Countered"),
                    ("Business_Counter_Pending", "Business Counter Pending Approval"),
                    ("Business_Countered", "Business Countered"),
                    (
                        "Accepted_Pending_Admin",
                        "Counter Accepted Pending Admin Approval",
                    ),
                    ("Under_Review", "Under Review"),
                    ("Counter_Declined", "Counter Declined - Pending Final Choice"),
                    ("Negotiation_Paused", "Negotiation Paused"),
                ],
                default="Under_Review",
                max_length=50,
            ),
        ),
    ]
