# Generated by Django 5.1.14 on 2026-06-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(blank=True, help_text='Unique Business Service identifier (automatically generated).', max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('rate', models.CharField(help_text="e.g. 'From $1,500 / project' or 'From $250 / hour'", max_length=255)),
                ('speed', models.CharField(help_text="e.g. '3-5 Days' or 'Ongoing'", max_length=255)),
                ('category', models.CharField(choices=[('Production', 'Production'), ('Legal', 'Legal'), ('Marketing', 'Marketing'), ('Design', 'Design'), ('Finance', 'Finance')], default='Production', max_length=100)),
                ('description', models.TextField()),
                ('bullet_points', models.TextField(help_text='Highlight points of the service, one point per line.')),
                ('gradient', models.CharField(default='from-purple-500 to-indigo-600', help_text="Tailwind CSS gradient classes (e.g. 'from-purple-500 to-indigo-600').", max_length=100)),
                ('target_audience', models.CharField(choices=[('business', 'Business'), ('creator', 'Creator'), ('both', 'Both')], default='both', help_text='Determine whether this service shows for businesses, creators, or both.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Only active services will be shown in the dashboards.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Service',
                'verbose_name_plural': 'Business Services',
            },
        ),
    ]
