# Generated by Django 5.1.14 on 2026-06-09 04:01

import django.db.models.deletion
from django.db import migrations, models

def create_default_categories(apps, schema_editor):
    ServiceCategory = apps.get_model('business_service', 'ServiceCategory')
    BusinessService = apps.get_model('business_service', 'BusinessService')
    
    # Create the default categories
    categories = ["Production", "Legal", "Marketing", "Design", "Finance"]
    cat_map = {}
    for name in categories:
        cat_obj, _ = ServiceCategory.objects.get_or_create(name=name)
        cat_map[name] = cat_obj.id
        
    # Convert old CharField values to stringified IDs of corresponding ServiceCategory
    for s in BusinessService.objects.all():
        if s.category in cat_map:
            s.category = str(cat_map[s.category])
            s.save()
        else:
            s.category = None
            s.save()

def reverse_categories(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('business_service', '0002_populate_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.RunPython(create_default_categories, reverse_categories),
        migrations.RemoveField(
            model_name='businessservice',
            name='gradient',
        ),
        migrations.AlterField(
            model_name='businessservice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='business_service.servicecategory'),
        ),
    ]
