# Generated by Django 5.1.14 on 2026-06-19 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_service', '0003_servicecategory_remove_businessservice_gradient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Project brief or inquiry details.')),
                ('budget', models.CharField(blank=True, help_text="Proposed budget for the request (e.g. '1500' or 'Flexible').", max_length=100, null=True)),
                ('timeline', models.CharField(choices=[('Standard', 'Standard Speed'), ('Urgent', 'Urgent / Rush'), ('Flexible', 'Flexible / Ongoing')], default='Standard', help_text='Timeline requirement.', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('declined', 'Declined')], default='pending', help_text='Status of the request.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(help_text='The service that is being requested.', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='business_service.businessservice')),
                ('user', models.ForeignKey(help_text='The user (creator or business) making the request.', on_delete=django.db.models.deletion.CASCADE, related_name='business_service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
