# Generated by Django 5.1.14 on 2026-06-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_service', '0005_populate_dummy_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessservicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Transferring to Company'), ('connected', 'Connected'), ('declined', 'Declined')], default='pending', help_text='Status of the request.', max_length=20),
        ),
    ]
