# Generated by Django 6.0.2 on 2026-09-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_service", "0006_alter_businessservicerequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessservice",
            name="speed",
            field=models.CharField(
                help_text="Estimated delivery or turnaround time in number of days (e.g. '5' or '3-5 Days').",
                max_length=255,
                verbose_name="Number of Days",
            ),
        ),
    ]
