# Generated by Django 6.0.2 on 2026-08-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WorkspacePayment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacepaymentnegotiation",
            name="final_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
