# Generated by Django 6.0.2 on 2026-08-05 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WorkspacePayment", "0002_alter_workspacepaymentnegotiation_final_price"),
        ("campegin", "0033_alter_campaignplatform_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Installment", max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_escrow", "In Escrow"),
                            ("payment_submitted", "Payment Submitted"),
                            ("released", "Released"),
                        ],
                        default="in_escrow",
                        max_length=50,
                    ),
                ),
                (
                    "receipt_image",
                    models.FileField(
                        blank=True, null=True, upload_to="payment_receipts/"
                    ),
                ),
                ("receipt_url", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_installments",
                        to="campegin.campaign",
                    ),
                ),
                (
                    "negotiation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="WorkspacePayment.workspacepaymentnegotiation",
                    ),
                ),
            ],
        ),
    ]
