# Generated by Django 6.0.2 on 2026-08-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WorkspacePayment", "0003_workspaceinstallment"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceinstallment",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workspaceinstallment",
            name="paid_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
