# Generated by Django 6.0.2 on 2026-08-05 18:08

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WorkspacePayment", "0004_workspaceinstallment_is_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceinstallment",
            name="negotiation",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installments",
                to="WorkspacePayment.workspacepaymentnegotiation",
            ),
        ),
    ]
