# Generated by Django 6.0.2 on 2026-08-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WorkspacePayment", "0005_alter_workspaceinstallment_negotiation"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacepaymentnegotiation",
            name="platform_charge",
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5),
        ),
    ]
