# Generated by Django 6.0.2 on 2026-08-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WorkspacePayment", "0006_workspacepaymentnegotiation_platform_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceinstallment",
            name="installment_type",
            field=models.CharField(
                choices=[
                    ("business", "Business Installment (Inbound)"),
                    ("creator", "Creator Installment (Outbound)"),
                ],
                default="creator",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workspacepaymentnegotiation",
            name="creator_platform_charge",
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
        ),
    ]
