# Generated by Django 6.0.2 on 2026-08-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WorkspacePayment", "0007_workspaceinstallment_installment_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacepaymentnegotiation",
            name="business_fee_is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workspacepaymentnegotiation",
            name="business_fee_paid_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspacepaymentnegotiation",
            name="creator_fee_is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workspacepaymentnegotiation",
            name="creator_fee_paid_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspacepaymentnegotiation",
            name="creator_fee_receipt_image",
            field=models.FileField(
                blank=True, null=True, upload_to="payment_receipts/"
            ),
        ),
    ]
