# Generated by Django 6.0.2 on 2026-08-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "WorkspacePayment",
            "0008_workspacepaymentnegotiation_business_fee_is_paid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacepaymentnegotiation",
            name="business_fee_receipt_image",
            field=models.FileField(
                blank=True, null=True, upload_to="payment_receipts/"
            ),
        ),
    ]
