# Generated by Django 6.0.2 on 2026-08-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "WorkspacePayment",
            "0009_workspacepaymentnegotiation_business_fee_receipt_image",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceinstallment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_escrow", "In Escrow"),
                    ("payment_submitted", "Payment Submitted"),
                    ("released", "Released"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
