# Generated by Django 6.0.2 on 2026-08-28 12:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WorkspacePayment", "0010_alter_workspaceinstallment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacepaymentnegotiation",
            name="creator_platform_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=1.5,
                help_text="Creator Platform Charge % (Must be between 1.50% and 10.00%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("1.50")),
                    django.core.validators.MaxValueValidator(Decimal("10.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="workspacepaymentnegotiation",
            name="platform_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=2.5,
                help_text="Business Platform Charge % (Must be between 2.50% and 10.00%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("2.50")),
                    django.core.validators.MaxValueValidator(Decimal("10.00")),
                ],
            ),
        ),
    ]
