# Generated by Django 6.0.2 on 2026-08-31 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "WorkspacePayment",
            "0011_alter_workspacepaymentnegotiation_creator_platform_charge_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceinstallment",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
