# Generated by Django 5.2.7 on 2026-06-05 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='average_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Awaiting Moderation', 'Awaiting Moderation'), ('Live', 'Live'), ('Completed', 'Completed'), ('Flagged', 'Flagged')], default='Pending', max_length=30),
        ),
        migrations.CreateModel(
            name='CreatorPortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='platform_api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('escrow', 'Escrow'), ('released', 'Released'), ('refund', 'Refunded'), ('deposit', 'Deposit')], max_length=30)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Released', 'Released'), ('In Escrow', 'In Escrow'), ('Refunded', 'Refunded')], max_length=30)),
                ('date', models.CharField(max_length=100)),
                ('receipt_url', models.CharField(blank=True, default='', max_length=255)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='platform_api.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
