# Generated by Django 5.1.14 on 2026-06-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='admin_review',
            field=models.TextField(blank=True, help_text='Provide review/rejection comments to the business if rejected.', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Live', 'Live'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
    ]
