# Generated by Django 5.1.14 on 2026-06-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('target_audience', models.CharField(choices=[('business', 'Business'), ('creator', 'Creator'), ('both', 'Both')], default='both', help_text='Determine whether these terms show for businesses, creators, or both.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Only active terms will be shown in the dashboards.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terms and Condition',
                'verbose_name_plural': 'Terms and Conditions',
            },
        ),
    ]
