# Generated by Django 5.1.14 on 2026-06-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandcondition',
            name='terms_id',
            field=models.CharField(blank=True, help_text='Unique terms identifier (automatically generated).', max_length=50, unique=True),
        ),
    ]
