# Generated by Django 6.0.2 on 2026-08-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terms", "0002_termsandcondition_terms_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termsandcondition",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("business", "Business"),
                    ("creator", "Creator"),
                    ("both", "Both"),
                    ("public", "Public"),
                ],
                default="both",
                help_text="Determine whether these terms show for businesses, creators, both, or public.",
                max_length=20,
            ),
        ),
    ]
