# Generated by Django 5.2.7 on 2026-06-28 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok')], default='instagram', max_length=30)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('reel', 'Reel')], default='photo', max_length=20)),
                ('views', models.CharField(blank=True, default='0', help_text="e.g. '1.2M', '840K'", max_length=50)),
                ('engagement_rate', models.FloatField(default=0.0, help_text='e.g. 8.4 for 8.4%')),
                ('brand', models.CharField(blank=True, default='', help_text='Sponsor/brand name, blank if organic', max_length=255)),
                ('post_link', models.URLField(blank=True, help_text='Live URL of the post', null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
