# Generated by Django 5.2.7 on 2026-06-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload a thumbnail image or screenshot for this post.', null=True, upload_to='portfolio/thumbnails/'),
        ),
    ]
