# Generated by Django 6.0.2 on 2026-07-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_portfolioitem_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioitem",
            name="proof_screenshot",
            field=models.ImageField(
                blank=True,
                help_text="Upload a screenshot of insights to verify views/engagement.",
                null=True,
                upload_to="portfolio/proofs/",
            ),
        ),
    ]
