# Generated by Django 5.1.14 on 2026-06-18 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_businessprofile_status_creatorprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_new_approved', models.BooleanField(default=True)),
                ('campaign_influencer_accepts', models.BooleanField(default=True)),
                ('campaign_deliverable_submitted', models.BooleanField(default=True)),
                ('payment_released', models.BooleanField(default=True)),
                ('platform_product_updates', models.BooleanField(default=True)),
                ('platform_weekly_report', models.BooleanField(default=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('plan', models.CharField(default='Pro', max_length=50)),
                ('card_last_four', models.CharField(blank=True, default='', max_length=4, null=True)),
                ('card_expiry', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('slack_connected', models.BooleanField(default=False)),
                ('google_analytics_connected', models.BooleanField(default=False)),
                ('hubspot_connected', models.BooleanField(default=False)),
                ('notion_connected', models.BooleanField(default=False)),
                ('zapier_connected', models.BooleanField(default=False)),
                ('theme', models.CharField(default='Light', max_length=20)),
                ('accent_color', models.CharField(default='oklch(0.55 0.27 285)', max_length=50)),
                ('sidebar_layout', models.CharField(default='Full', max_length=20)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='user.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CreatorPayoutMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_methods', to='user.creatorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CreatorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_new_brand_requests', models.BooleanField(default=True)),
                ('email_campaign_updates', models.BooleanField(default=True)),
                ('email_payment_received', models.BooleanField(default=True)),
                ('email_profile_views', models.BooleanField(default=False)),
                ('email_platform_news', models.BooleanField(default=False)),
                ('push_brand_requests', models.BooleanField(default=True)),
                ('push_message_replies', models.BooleanField(default=True)),
                ('push_payout_completed', models.BooleanField(default=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('tax_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('tax_form_submitted', models.BooleanField(default=False)),
                ('plan', models.CharField(default='Creator Pro', max_length=50)),
                ('currency', models.CharField(default='USD ($)', max_length=20)),
                ('rate_card_note', models.TextField(blank=True, default='', null=True)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='user.creatorprofile')),
            ],
        ),
    ]
