# Generated by Django 5.1.14 on 2026-06-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorsettings',
            name='accent_color',
            field=models.CharField(default='oklch(0.7 0.2 25)', max_length=50),
        ),
        migrations.AddField(
            model_name='creatorsettings',
            name='sidebar_layout',
            field=models.CharField(default='Full', max_length=20),
        ),
        migrations.AddField(
            model_name='creatorsettings',
            name='theme',
            field=models.CharField(default='Light', max_length=20),
        ),
    ]
