# Generated by Django 6.0.2 on 2026-07-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Setting", "0002_creatorsettings_accent_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creatorpayoutmethod",
            name="details",
        ),
        migrations.RemoveField(
            model_name="creatorpayoutmethod",
            name="method_type",
        ),
        migrations.AddField(
            model_name="creatorpayoutmethod",
            name="account_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="creatorpayoutmethod",
            name="bank_book_photo_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="creatorpayoutmethod",
            name="bank_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="creatorpayoutmethod",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
