# Generated by Django 6.0.2 on 2026-07-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Setting", "0003_remove_creatorpayoutmethod_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creatorpayoutmethod",
            name="bank_book_photo_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
