# Generated by Django 6.0.2 on 2026-07-19 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Setting", "0004_alter_creatorpayoutmethod_bank_book_photo_url"),
        ("user", "0017_alter_country_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessPayoutMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "bank_book_photo_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_methods",
                        to="user.businessprofile",
                    ),
                ),
            ],
        ),
    ]
