# Generated by Django 6.0.2 on 2026-07-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RateCard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratecard",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="ratecard",
            name="district",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="ratecard",
            name="medium",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="ratecard",
            name="province",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
