# Generated by Django 5.1.14 on 2026-06-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('restricted', 'Restricted')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('restricted', 'Restricted')], default='pending', max_length=20),
        ),
    ]
