# Generated by Django 5.2.7 on 2026-06-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_businessprofile_status_creatorprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_types',
            field=models.ManyToManyField(blank=True, related_name='businesses', to='user.businesstype'),
        ),
    ]
