# Generated by Django 5.1.14 on 2026-06-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_businesstype_businessprofile_business_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='business_document',
            field=models.FileField(blank=True, null=True, upload_to='business_documents/'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_reg_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='verification_documents_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
