# Generated by Django 5.1.14 on 2026-06-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_businessprofile_business_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='document_back',
            field=models.FileField(blank=True, null=True, upload_to='creator_documents/'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='document_front',
            field=models.FileField(blank=True, null=True, upload_to='creator_documents/'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='document_type',
            field=models.CharField(blank=True, choices=[('nic', 'NIC'), ('passport', 'Passport'), ('driving_license', 'Driving License')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='other_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='verification_documents_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
