# Generated by Django 5.1.14 on 2026-06-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_creatorprofile_document_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='otp_method',
            field=models.CharField(choices=[('email', 'Email'), ('mobile', 'Mobile')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='otp_method',
            field=models.CharField(choices=[('email', 'Email'), ('mobile', 'Mobile')], default='email', max_length=10),
        ),
    ]
