# Generated by Django 6.0.2 on 2026-07-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_country_businessprofile_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorprofile",
            name="saved_brands",
            field=models.ManyToManyField(
                blank=True, related_name="saved_by_creators", to="user.businessprofile"
            ),
        ),
    ]
