# Generated by Django 6.0.2 on 2026-07-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_medium_creatorprofile_mediums_province_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="province",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="province",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
