# Generated by Django 6.0.2 on 2026-07-16 11:22

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_alter_province_options_province_sort_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medium",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="country",
            name="country_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="currency",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="medium",
            name="country",
            field=modelcluster.fields.ParentalKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mediums",
                to="user.country",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medium",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="medium",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "country",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="user.country",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts_list",
                        to="user.province",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
