# Generated by Django 6.0.2 on 2026-07-16 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_alter_medium_options_country_country_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businesses",
                to="user.district",
            ),
        ),
    ]
