# Generated by Django 6.0.2 on 2026-07-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_creatorprofile_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="mediums",
            field=models.ManyToManyField(
                blank=True, related_name="businesses", to="user.medium"
            ),
        ),
    ]
