# Generated by Django 6.0.2 on 2026-07-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_businessprofile_mediums"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
    ]
