# Generated by Django 6.0.2 on 2026-07-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_alter_country_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorrate",
            name="max_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="creatorrate",
            name="min_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
    ]
