# Generated by Django 6.0.2 on 2026-07-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_creatorrate_max_price_creatorrate_min_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="niche",
            options={
                "ordering": ["name"],
                "verbose_name": "Niche",
                "verbose_name_plural": "Niches",
            },
        ),
        migrations.AddField(
            model_name="niche",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Checked = active/visible; Unchecked = inactive/hidden",
                verbose_name="Active",
            ),
        ),
    ]
