# Generated by Django 6.0.2 on 2026-08-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_alter_niche_options_niche_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorsocialaccount",
            name="proof_link",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="creatorsocialaccount",
            name="engagement_rate",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="creatorsocialaccount",
            name="followers_count",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="creatorsocialaccount",
            name="platform",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="creatorsocialaccount",
            name="username",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
