# Generated by Django 6.0.2 on 2026-08-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0020_creatorsocialaccount_proof_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorsocialaccount",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="Verified by Super Admin"
            ),
        ),
    ]
