# Generated by Django 6.0.2 on 2026-08-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0021_creatorsocialaccount_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorprofile",
            name="deletion_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="deletion_request_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="deletion_requested",
            field=models.BooleanField(
                default=False, help_text="Creator has requested account deletion"
            ),
        ),
    ]
