# Generated by Django 6.0.2 on 2026-08-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0022_creatorprofile_deletion_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorprofile",
            name="deletion_decline_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
