# Generated by Django 6.0.2 on 2026-08-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0023_creatorprofile_deletion_decline_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="deletion_decline_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="deletion_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="deletion_request_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="deletion_requested",
            field=models.BooleanField(
                default=False, help_text="Business has requested account deletion"
            ),
        ),
    ]
