# Generated by Django 6.0.2 on 2026-08-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0024_businessprofile_deletion_decline_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="cover_image_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="cover_image_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
