# Generated by Django 6.0.2 on 2026-08-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0025_businessprofile_cover_image_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("otp_code", models.CharField(max_length=6)),
                (
                    "otp_method",
                    models.CharField(
                        choices=[("email", "Email"), ("mobile", "Mobile")],
                        default="email",
                        max_length=10,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("business", "Business"), ("influencer", "Creator")],
                        default="influencer",
                        max_length=20,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[("signin", "Sign In"), ("signup", "Sign Up")],
                        default="signup",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "OTP Verification",
                "verbose_name_plural": "OTP Verifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
