# Generated by Django 6.0.2 on 2026-09-02 05:10

from django.db import migrations, models


def remap_audiences(apps, schema_editor):
    PrivacyPolicy = apps.get_model("privacy_policy", "PrivacyPolicy")
    for p in PrivacyPolicy.objects.all():
        audience = (p.target_audience or "").lower()
        if "creator" in audience:
            p.target_audience = "creator"
            if p.policy_id and not p.policy_id.endswith("-CR"):
                p.policy_id = p.policy_id[:7] + "-CR" if len(p.policy_id) >= 7 else p.policy_id + "-CR"
            p.save()
        elif "business" in audience or "brand" in audience:
            p.target_audience = "business"
            if p.policy_id and not p.policy_id.endswith("-BU"):
                p.policy_id = p.policy_id[:7] + "-BU" if len(p.policy_id) >= 7 else p.policy_id + "-BU"
            p.save()
        elif audience not in ("public", "creator", "business"):
            p.target_audience = "public"
            if p.policy_id and not p.policy_id.endswith("-PU"):
                p.policy_id = p.policy_id[:7] + "-PU" if len(p.policy_id) >= 7 else p.policy_id + "-PU"
            p.save()


class Migration(migrations.Migration):

    dependencies = [
        ("privacy_policy", "0002_privacypolicy_delete_privacypolicyguide"),
    ]

    operations = [
        migrations.RunPython(remap_audiences, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="privacypolicy",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("public", "Public (Landing Page)"),
                    ("creator", "Creator"),
                    ("business", "Business"),
                ],
                default="public",
                help_text="Determine whether this privacy policy shows for public, creator, or business.",
                max_length=50,
            ),
        ),
    ]
