# Generated by Django 6.0.2 on 2026-09-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privacy_policy", "0003_alter_privacypolicy_target_audience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privacypolicy",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("public", "Public (Landing Page)"),
                    ("creator", "Creator"),
                    ("business", "Business"),
                    ("both", "Both"),
                ],
                default="public",
                help_text="Determine whether this privacy policy shows for public, creator, business, or both.",
                max_length=50,
            ),
        ),
    ]
