# Generated by Django 5.1.14 on 2026-06-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(default='fas fa-bell', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('signup', 'User Registration'), ('campaign', 'Campaign Created'), ('payment', 'Escrow / Payment'), ('compliance', 'Compliance & Dispute')], default='signup', max_length=50),
        ),
    ]
