# Generated by Django 5.1.14 on 2026-06-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_icon_alter_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
