# Generated by Django 6.0.2 on 2026-08-03 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_target_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="target_role",
            field=models.CharField(
                choices=[
                    ("all", "All Roles"),
                    ("admin", "Admin Only"),
                    ("business", "Business Only"),
                    ("creator", "Creator Only"),
                ],
                default="all",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
