# Generated by Django 5.1.14 on 2026-06-08 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campegin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('file_attachment', models.CharField(blank=True, default='', max_length=255)),
                ('time', models.CharField(max_length=50)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='campegin.campaign')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Safety / Guidelines', 'Safety / Guidelines'), ('Escrow Protection', 'Escrow Protection'), ('Contract Scope Dispute', 'Contract Scope Dispute'), ('Deliverable Audit', 'Deliverable Audit')], default='Safety / Guidelines', max_length=100)),
                ('review_text', models.TextField()),
                ('target_audience', models.CharField(choices=[('business', 'Business'), ('creator', 'Creator'), ('both', 'Both')], default='both', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reviews', to='campegin.campaign')),
            ],
        ),
    ]
