# Generated by Django 5.1.14 on 2026-06-06 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_monitor', '0001_initial'),
        ('platform_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Safety / Guidelines', 'Safety / Guidelines'), ('Escrow Protection', 'Escrow Protection'), ('Contract Scope Dispute', 'Contract Scope Dispute'), ('Deliverable Audit', 'Deliverable Audit')], default='Safety / Guidelines', max_length=100)),
                ('review_text', models.TextField()),
                ('target_audience', models.CharField(choices=[('business', 'Business'), ('creator', 'Creator'), ('both', 'Both')], default='both', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reviews', to='platform_api.campaign')),
            ],
        ),
    ]
